### PR TITLE
Setup webpack module bundler

### PR DESCRIPTION
**Pull request by alesshh**
## Proposal

Use webpack module bundler to front end scripts.

- Added `npm-run-all` development dependency to run express server with webpack watcher at same time;
- Use `jquery`, `socker-io.client`, `sentry` npm packages instead cdn;

### How to test?
Test all things

### CODE REVIEW

**Comment by juliemar** [comment]
My contribution to this PR will be only testing because my front-end knowledge is not sufficient to have a great suggestion and great review :)

**Comment by juliemar** [comment]
Is there a way to reduce the size of office-bundle.js? after this PR the office page sise raised from 440k to 1.4MB. Increased 3 times :O

Network transfer with Current version:
image


Network transfer with This PR:
image

**Comment by lccezinha** [comment]
I'm not familiar with web pack too, maybe a more experienced frontend could help in this one.

**Comment by juliemar** [comment]
@jeantoledo could you review this PR? :)

**Comment by alesshh** [comment]
> Is there a way to reduce the size of office-bundle.js? after this PR the office page size raised from 440k to 1.4MB. Increased 3 times :O
> 
> Network transfer with Current version:
> image
> 
> Network transfer with This PR:
> image

Hey @juliemar 1.4MB is the development bundle size. Below, the production bundle comparision.

Current:
Screen Shot 2019-05-07 at 10 56 09

Bundled with webpack:
Screen Shot 2019-05-06 at 14 04 29

**Comment by juliemar** [comment]
Hi @alesshh I fixed the bug of "get menu" in this PR https://github.com/ResultadosDigitais/matrix/pull/140 you can merge this PR in your branch ;)

**Comment by juliemar** [comment]
Hi @alesshh I merged this PR #140

**Comment by juliemar** [comment]
- [ ] Execute login via Google Credentials
- [ ] Navigate into all rooms
- [ ] Notify clients when another connected user go away
- [ ] Redirect to /home when unlogged user enter in /office
- [ ] Open external meeting when the user enter in a room
- [ ] On reload, keep user in the last room
- [ ] Notify when an user enter in a room
- [ ] Identify when user in a video meeting
- [ ] Right click to call other user to my room

**Comment by juliemar** [comment]
I created a snapshot tag with the previous version without webpack https://github.com/ResultadosDigitais/matrix/tree/v0.1 @alesshh Let's Ship it

**Pull request merged**
