### PR TITLE
Adds matrix song when room invite is received

### LINKED ISSUE #312: Play sound while invite dialog is shown
When I'm with #matrix tab running in background, my coworkers always need to send me a Slack message with "hey! we're inviting you to a meeting inside the #matrix". 

Almost every invite notification that I receive goes unnoticed. So it would be very good have an incoming call sound playing while invite dialog is shown (Skype or Slack like).

## Description

Play a ringtone sound (something like [this one](https://actions.google.com/sounds/v1/household/phone_ringing.ogg)) while invite dialog is shown to user. When the user cancel or accept the invite the sound stops playing.

### Additional context

Offtopic: Here at my work we're using #matrix and it's working quite good. Probably I'll be here time to time with some new ideas or bugs. Hope I can help with some PRs too but React and Node aren't my cup of tea :laughing:

### PR DESCRIPTION
**Pull request by phiter**
### Description

resolves #312

### How to test?

1. Join a meeting
2. Invite another user to that meeting

### Expected behavior

The other user should listen to the matrix ringtone until they close or accept the invite solicitation.

### CODE REVIEW

**Comment by phiter** [comment]
Sure, in a few minutes.

**Comment by phiter** [comment]
@juliemar just pushed it! Seems like the develop branch had new eslint rules. I'll update my code.

**Comment by phiter** [comment]
Code climate is reporting a weird error, seems related to ESLint but I don't know what it is.

**Comment by angeliski** [comment]
I didn't find the problem too. I will mark the issue as invalid.
@juliemar I tested locally, Can we merge this?

**Comment by juliemar** [comment]
@all-contributors please add  @phiter for code

**Pull request merged**
